import importlib.util
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture(scope="session")
def mock_dir(tmp_path_factory) -> Path:
    """Fresh mock data (offline sphere mesh) generated by scripts/make_mock_data.py."""
    out = tmp_path_factory.mktemp("mock")
    spec = importlib.util.spec_from_file_location("make_mock_data", ROOT / "scripts" / "make_mock_data.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    argv = sys.argv
    sys.argv = ["make_mock_data.py", "--out", str(out), "--n", "12", "--no-real-mesh"]
    try:
        mod.main()
    finally:
        sys.argv = argv
    return out


@pytest.fixture(scope="session")
def client(mock_dir, monkeypatch_session) -> TestClient:
    from app.main import app
    from app.store import load_store

    monkeypatch_session.delenv("GEMINI_API_KEY", raising=False)
    app.state.store = load_store(mock_dir / "data", mock_dir / "audio")
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="session")
def monkeypatch_session():
    mp = pytest.MonkeyPatch()
    yield mp
    mp.undo()
